allow clients to set QUERY_TAG parameter via context
snowflakedb/gosnowflake pull request #427
Opened 2021-05-11 22:18 UTC by GregOwen

### Description
1. Add new `WithQueryTag` method to allow clients to pass the `QUERY_TAG` parameter to a query via the context
2. Add test to verify that we're setting the tag correctly

### Checklist
- [X] Code compiles correctly
- [ ] Run ``make fmt`` to fix inconsistent formats
- [X] Run ``make lint`` to get lint errors and fix all of them
- [X] Created tests which fail without the change (if possible)
- [x] All tests passing
- [ ] Extended the README / documentation, if necessary

2021-05-11 22:19 UTC, GregOwen commented
@sfc-gh-jbahk here's the second of the two PRs I mentioned. This one should hopefully be pretty straightforward.

2021-05-12 23:34 UTC, GregOwen commented
@sfc-gh-jbahk Sorry for the delay in getting back to you. Some of our customers have asked us to include Sigma-level metadata (username, Sigma document) for each Snowflake query so that they can do automated attribution of their Sigma-initiated Snowflake usage. Right now, we add this metadata as a JSON blob in a comment at the end of the query, but our customers have asked us to move this information into the `Query Tag` column so that it's easier for them to extract and analyze within Snowflake.

2021-05-13 18:14 UTC, sfc-gh-jbahk commented
@GregOwen I see potential conflicts with this approach wherein the statement parameters that the customers might pass into the statement could either throw errors, not accepted by our server or conflict with our internal parameters. Another issue would be security threats including, but not limited to, injections. Could you give me a more specific example? Thanks.

2021-05-13 20:38 UTC, GregOwen commented
That makes sense. We probably don't need this to be as wide an interface as it currently is.
Our requirements are:
1. we can pass a JSON blob containing metadata per-query
2. the per-query metadata will be associated with the query in a way that Sigma customers can parse and analyze within Snowflake (in particular, we don't want the JSON blob to be part of a comment within the text of the query itself)

The way that we're currently using it is something like this:
```
params := make(map[string]string)
params["QUERY_TAG"] = fmt.Sprintf(`{"request-id":"%s","email":"%s"}`, requestId, email) // possibly Sigma document ID, etc.
ctx = WithContextStatementParameters(ctx, params)

// execute the query with the given context
```

2021-05-13 20:43 UTC, sfc-gh-jbahk commented
@GregOwen I see. Where would these parameters be used? Will it be inserted as a value of a column?

2021-05-13 21:44 UTC, GregOwen commented
@sfc-gh-jbahk The idea is that the metadata will show up as a `Query Tag` column in the customer's History view. Here's an example:

<img width="1790" alt="Screen Shot 2021-05-13 at 1 50 22 PM" src="https://user-images.githubusercontent.com/1291832/118191398-5937f480-b3f9-11eb-9138-f65609736eef.png">

This way a customer's Snowflake admin can use Snowflake to ask questions like "how many queries did Sigma run?" or "which Sigma documents are responsible for my increased Snowflake usage?".

2021-05-17 23:20 UTC, sfc-gh-jbahk commented
@GregOwen I've reviewed this with my team and think it should be okay to move forward but if you can change the code to be less generic such that the statement context doesn't accept anything the user inputs but rather tailor it towards a query tag. Maybe this can be of some use: https://docs.snowflake.com/en/sql-reference/parameters.html#query-tag.

2021-05-19 01:54 UTC, GregOwen commented
@sfc-gh-jbahk sounds great - I reworked it to be more precisely targeted at `QUERY_TAG` and added a test

2021-06-21 16:18 UTC, sfc-gh-jbahk commented
@GregOwen can you rebase and push this branch?

2021-06-21 20:25 UTC, GregOwen commented
@sfc-gh-jbahk done

2021-06-21 23:20 UTC, GregOwen commented
Test failures look like they're related to test infrastructure/secrets:

```
Run ./ci/test.sh
  ./ci/test.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    GOROOT: /opt/hostedtoolcache/go/1.15.13/x64
    PARAMETERS_SECRET: 
    CLOUD_PROVIDER: AWS
gpg: gcry_kdf_derive failed: Invalid data
gpg: decryption failed: No secret key
Error: Process completed with exit code 2.
```

2022-05-20 16:29 UTC, tampajohn commented
@sfc-gh-jbahk any idea if/when this is planned to be merged?  Or what needs to be done to get it mergeable?

2022-05-20 22:09 UTC, sfc-gh-jbahk commented
@sfc-gh-cshi can you take a look at this PR and see if it's something the go driver needs/wants? cc: @sfc-gh-hkapre

2023-05-17 06:58 UTC, DmitryMaletin commented
@sfc-gh-jbahk  is there any plan to complete the merge?

2023-10-18 09:41 UTC, sfc-gh-pfus commented
Hi @tampajohn ! Do you still need this? Can you rebase and solve conflicts and align to new test helper function?

2023-10-18 09:44 UTC, sfc-gh-pfus commented
Sorry @tampajohn , I meant @GregOwen of course!

2023-10-19 19:51 UTC, GregOwen commented
@sfc-gh-pfus yes, we would still like to merge this PR. Can you confirm that somebody at Snowflake will be responsive to changes to this PR? Last time we got it to the 1-yard line but couldn't get it merged because each new commit requires manual re-approval to run the CI tests.

2023-10-20 07:23 UTC, sfc-gh-pfus commented
Yes, now go driver migrated to another team. I merged/closed/handled 13 PRs this week, so I believe that we can handle one more :)

2023-11-13 20:12 UTC, GregOwen commented
One sec; making sure that Sigma knows about the CLA and is comfortable with me signing it

2023-11-30 17:22 UTC, debugmiller commented
Would love to see this merged in!

2023-12-04 16:57 UTC, GregOwen commented
I have read the CLA Document and I hereby sign the CLA

2023-12-04 19:05 UTC, GregOwen commented
@sfc-gh-pfus I've rebased and we've signed the CLA (it took a while to get legal approval for that). Could you please kick off the tests?

2023-12-05 10:15 UTC, sfc-gh-pfus requested changes

2023-12-05 10:15 UTC, sfc-gh-pfus commented on statement_test.go
> +		if !rows.Next() {
We have some assert functions, can you use them?
https://github.com/snowflakedb/gosnowflake/blob/master/assert_test.go

2023-12-05 10:15 UTC, sfc-gh-pfus commented on util.go
>  	requestID, ok := ctx.Value(snowflakeRequestIDKey).(UUID)
Can you add some info to doc.go? I'd prefer having it before `Query request ID` section.

2023-12-05 10:17 UTC, sfc-gh-pfus commented
Hi @GregOwen ! Thanks again for your contribution. I left some two suggestions and in the meantime started jobs.

2023-12-05 11:01 UTC, sfc-gh-pfus commented
Your test hangs. I believe this is because you forgot to defer rows closing.

2023-12-05 16:06 UTC, GregOwen commented
@sfc-gh-pfus I've pushed changes that should address your comments; let me know if they look good to you

2023-12-06 08:51 UTC, sfc-gh-pfus approved these changes

2023-12-06 10:27 UTC, sfc-gh-pfus commented
Hi @GregOwen ! All of your checks are green (I fixed a flaky test in the meantime). Can you rebase your PR? I can't do it myself.

2023-12-06 16:19 UTC, GregOwen commented
@sfc-gh-pfus rebased. It looks like we may get stuck in a "need to rebase" --> "need approval to run tests" loop since we're in different timezones. I'm based in EST; should we try to coordinate tomorrow so that I make my changes first thing in the morning my time (which I'm guessing will line up with the end of your workday)?

2023-12-07 07:31 UTC, merged

2023-12-07 07:33 UTC, sfc-gh-pfus commented
Hi @GregOwen ! Actually I wanted to do it in the morning, before no one from merges from my team ;) Thank you very much, your commit will be released in January!